package dk.cachet.carp.analytics.domain.execution

import dk.cachet.carp.analytics.domain.data.ExecutionOutput
import dk.cachet.carp.common.application.UUID
import kotlinx.serialization.Serializable

/**
 * Represents the result of a completed workflow execution.
 *
 * This sealed interface enables structured results to be reported back to users or stored persistently.
 * Subtypes may include different levels of detail, such as output references and visualization artifacts.
 */
@Serializable
sealed interface ExecutionResult
{
    val executionId: UUID
    val status: ExecutionStatus
    val outputs: List<ExecutionOutput>?
}

/**
 * Describes a visual or downloadable artifact generated by a workflow step,
 * such as a PNG plot, PDF report, or JSON file.
 *
 * @param uri Absolute or relative URI to the artifact (file path, API route, etc.).
 * @param name Human-readable name for display purposes.
 * @param type Enum describing the artifact type (e.g., file, image).
 * @param mimeType Optional MIME type (e.g., "image/png", "application/pdf").
 */
@Serializable
data class ExecutionArtifact(
    val uri: String,
    val name: String,
    val type: ArtifactType,
    val mimeType: String? = null
)

/**
 * A basic execution result that includes structured outputs and optional visualization artifacts.
 *
 * Use this as the default implementation for workflows that produce both tabular and visual outputs.
 */
@Serializable
data class BasicExecutionResult(
    override val executionId: UUID,
    override val status: ExecutionStatus,
    override val outputs: List<ExecutionOutput>?,
    val artifacts: List<ExecutionArtifact> = emptyList()
) : ExecutionResult
