package dk.cachet.carp.analytics.application.plan

import dk.cachet.carp.analytics.domain.data.FileFormat
import dk.cachet.carp.analytics.domain.data.FileLocation
import dk.cachet.carp.analytics.domain.data.OutputDataSpec
import dk.cachet.carp.common.application.UUID
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull

/**
 * Comprehensive unit tests for [ResolvedOutput] using unified DataLocation model.
 *
 * Tests:
 * - Creation with specs and resolved locations
 * - Accessing spec and location properties
 * - Field preservation across creation
 * - Location path access via helper method
 * - Path generation for outputs with empty initial path
 */
class ResolvedOutputTest
{
    private fun createTestSpec(
        id: UUID = UUID.randomUUID(),
        name: String = "test-output",
        description: String = "Test output"
    ): OutputDataSpec
    {
        return OutputDataSpec(
            id = id,
            name = name,
            description = description,
            location = FileLocation(
                path = "", // Empty, will be generated at planning time
                format = FileFormat.CSV
            ),
            format = FileFormat.CSV
        )
    }

    private fun createTestLocation( path: String = "/workspace/output/output.csv" ): FileLocation
    {
        return FileLocation(
            path = path,
            format = FileFormat.CSV
        )
    }

    // Creation Tests

    @Test
    fun `ResolvedOutput creation with valid spec and location succeeds`()
    {
        val spec = createTestSpec()
        val location = createTestLocation()

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( spec, resolved.spec )
        assertEquals( location, resolved.location )
    }

    @Test
    fun `ResolvedOutput preserves all spec metadata`()
    {
        val outputId = UUID.randomUUID()
        val spec = createTestSpec(
            id = outputId,
            name = "my-output",
            description = "My output description"
        )
        val location = createTestLocation()

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( outputId, resolved.spec.id )
        assertEquals( "my-output", resolved.spec.name )
        assertEquals( "My output description", resolved.spec.description )
        assertEquals( FileFormat.CSV, resolved.spec.format )
    }

    // Location Access Tests

    @Test
    fun `ResolvedOutput provides access to unified DataLocation`()
    {
        val spec = createTestSpec()
        val resolvedPath = "/workspace/output/specific/path/results.csv"
        val location = FileLocation(
            path = resolvedPath,
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertIs<FileLocation>( resolved.location )
        assertEquals( resolvedPath, resolved.location.path )
        assertEquals( FileFormat.CSV, resolved.location.format )
    }

    @Test
    fun `ResolvedOutput helper method getPath returns correct path`()
    {
        val spec = createTestSpec()
        val location = createTestLocation( "/workspace/results.csv" )

        val resolved = ResolvedOutput( spec = spec, location = location )

        val path = resolved.getPath()
        assertNotNull( path )
        assertEquals( "/workspace/results.csv", path )
    }

    // Auto-Generated Path Tests

    @Test
    fun `ResolvedOutput with auto-generated path format`()
    {
        val spec = createTestSpec( name = "results" )
        // Path was empty in spec, generated by planner
        val location = FileLocation(
            path = "/workspace/outputs/Process Data/results.csv",
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        // Spec still has empty path, but resolved location has generated path
        assertEquals( "", ( resolved.spec.location as FileLocation ).path )
        assertEquals( "/workspace/outputs/Process Data/results.csv", ( resolved.location as FileLocation ).path )
    }

    @Test
    fun `ResolvedOutput with explicit path overrides generation`()
    {
        val spec = OutputDataSpec(
            id = UUID.randomUUID(),
            name = "report",
            location = FileLocation(
                path = "/custom/output/location/report.csv", // Explicit path
                format = FileFormat.CSV
            ),
            format = FileFormat.CSV
        )
        val location = FileLocation(
            path = "/custom/output/location/report.csv",
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        // Explicit path is preserved
        assertEquals( "/custom/output/location/report.csv", ( resolved.spec.location as FileLocation ).path )
        assertEquals( "/custom/output/location/report.csv", ( resolved.location as FileLocation ).path )
    }


    // Field Preservation Tests


    @Test
    fun `ResolvedOutput preserves location through construction`()
    {
        val spec = createTestSpec()
        val originalPath = "/workspace/output/deep/nested/path/results.csv"
        val location = FileLocation(
            path = originalPath,
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        val retrievedPath = (resolved.location as FileLocation).path
        assertEquals( originalPath, retrievedPath )
    }


    // Different Location Format Tests


    @Test
    fun `ResolvedOutput works with different file formats`()
    {
        val spec = OutputDataSpec(
            id = UUID.randomUUID(),
            name = "json-output",
            location = FileLocation( path = "", format = FileFormat.JSON ),
            format = FileFormat.JSON
        )
        val location = FileLocation(
            path = "/workspace/outputs/data.json",
            format = FileFormat.JSON
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( FileFormat.JSON, ( resolved.location as FileLocation ).format )
    }

    @Test
    fun `ResolvedOutput works with Parquet format`()
    {
        val spec = OutputDataSpec(
            id = UUID.randomUUID(),
            name = "parquet-output",
            location = FileLocation( path = "", format = FileFormat.PARQUET ),
            format = FileFormat.PARQUET
        )
        val location = FileLocation(
            path = "/workspace/outputs/data.parquet",
            format = FileFormat.PARQUET
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( FileFormat.PARQUET, ( resolved.location as FileLocation ).format )
    }


    // Location Path Variants Tests


    @Test
    fun `ResolvedOutput handles absolute paths`()
    {
        val spec = createTestSpec()
        val location = FileLocation(
            path = "/absolute/path/to/output.csv",
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( "/absolute/path/to/output.csv", resolved.getPath() )
    }

    @Test
    fun `ResolvedOutput handles workspace-relative paths`()
    {
        val spec = createTestSpec()
        val location = FileLocation(
            path = "/workspace/outputs/step-name/output.csv",
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        assertEquals( "/workspace/outputs/step-name/output.csv", resolved.getPath() )
    }

    @Test
    fun `ResolvedOutput preserves format for extension inference`()
    {
        val spec = createTestSpec()
        // Planner can use location.format to infer extension
        val location = FileLocation(
            path = "/workspace/outputs/step-1/output.csv",
            format = FileFormat.CSV
        )

        val resolved = ResolvedOutput( spec = spec, location = location )

        // When generating filenames, executor can use:
        // "${path.substring(0, path.lastIndexOf('/'))}/output${format.extension}"
        assertEquals( FileFormat.CSV, ( resolved.location as FileLocation ).format )
        assertEquals( "csv", resolved.location.format.extension)
    }


    // Multiple Output Tests


    @Test
    fun `ResolvedOutput with multiple outputs from same step`()
    {
        val output1Id = UUID.randomUUID()
        val output2Id = UUID.randomUUID()

        val spec1 = OutputDataSpec(
            id = output1Id,
            name = "results-1",
            location = FileLocation( path = "", format = FileFormat.CSV ),
            format = FileFormat.CSV
        )
        val spec2 = OutputDataSpec(
            id = output2Id,
            name = "results-2",
            location = FileLocation( path = "", format = FileFormat.JSON ),
            format = FileFormat.JSON
        )

        val location1 = FileLocation(
            path = "/workspace/outputs/step-name/results-1.csv",
            format = FileFormat.CSV
        )
        val location2 = FileLocation(
            path = "/workspace/outputs/step-name/results-2.json",
            format = FileFormat.JSON
        )

        val resolved1 = ResolvedOutput( spec = spec1, location = location1 )
        val resolved2 = ResolvedOutput( spec = spec2, location = location2 )

        assertEquals( "/workspace/outputs/step-name/results-1.csv", resolved1.getPath() )
        assertEquals( "/workspace/outputs/step-name/results-2.json", resolved2.getPath() )
    }
}
