package dk.cachet.carp.analytics.application.data

import dk.cachet.carp.data.application.DataStreamBatch

/**
 * Represents a unit of data managed by the analytics runtime.
 *
 * Used within the [DataRegistry] to store and retrieve intermediate outputs from steps.
 * Implementations may encapsulate different storage forms such as in-memory data,
 * files, etc...
 */
sealed interface DataHandle

/**
 * A [DataHandle] representing data stored in memory during execution.
 *
 * Typically used to transfer step output datasets that are not persisted to disk.
 *
 * @param dataset A [DataStreamBatch] containing the data.
 */
data class InMemoryData( val dataset: DataStreamBatch ) : DataHandle

/**
 * A [DataHandle] representing a file produced or consumed by a workflow step.
 *
 * May reference result files (e.g., CSV, plots, summaries) generated by processes.
 *
 * @param path The absolute or relative path to the file.
 * @param mimeType Optional MIME type, e.g., "text/csv" or "image/png".
 */
data class FileData( val path: String, val mimeType: String? = null ) : DataHandle
