# Verify pull requests on develop.

name: Verify pull requests

on:
  pull_request:
    branches: 
      - develop

jobs:
  unit-tests-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build and test
        run: ./gradlew build 

  verify-typescript-declarations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
         
      - name: Build and test
        run: ./gradlew verifyTsDeclarations 
        
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Code analysis
        run: ./gradlew detektPasses 
